# Generated by Django 4.1.4 on 2023-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_handwriting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, verbose_name='Символ')),
                ('binary', models.CharField(max_length=255, verbose_name='Бинарное представление')),
            ],
            options={
                'verbose_name': 'Бинари',
                'verbose_name_plural': 'Бинари',
                'db_table': 'binary_dicts',
            },
        ),
    ]
