# Generated by Django 4.1.4 on 2023-07-18 17:27
import random
import time

from django.db import migrations
from django.db.migrations import RunPython


def check_binary(line):
    for i in line:
        if i == "1":
            return True
    return False


def collect_binary(apps, schema_editor):
    BinaryDict = apps.get_model("api", "BinaryDict")
    list_symbol = [
        "А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ф",
        "Х", "Ц", "Ч", "Ш", "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K",
        "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "а", "б", "в", "г", "д", "е", "ё",
        "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ы",
        "ь", "э", "ю", "я", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r",
        "s", "t", "u", "v", "w", "x", "y", "z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "!", "@", "#", "$",
        "%", "^", "&", "*", "(", ")", "-", "_", "+", "=", "{", "}", "[", "]", "|", "", ":", ";", "'", "\"", "<", ">",
        ".", ",", "?", "/", "~", " "
    ]
    list_binary = []
    random.seed(time.time())
    for symbol in list_symbol:
        binary = "".join([random.choice(["0", "1", "1", "0"]) for i in range(8)])
        while not check_binary(binary) or binary in list_binary:
            binary = "".join([random.choice(["0", "1", "1", "0"]) for i in range(8)])
        list_binary.append(binary)
        BinaryDict.objects.create(
            symbol=symbol,
            binary=binary
        )


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_binarydict'),
    ]

    operations = [
        RunPython(collect_binary),
    ]
