# Generated by Django 4.0 on 2023-09-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Участник книги',
                'verbose_name_plural': 'Участники книги',
                'db_table': 'book_members',
            },
        ),
    ]
