# Generated by Django 4.1.4 on 2023-07-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230718_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Тип ответа',
                'verbose_name_plural': 'Типы ответов',
                'db_table': 'type_answers',
            },
        ),
        migrations.AlterModelOptions(
            name='binarydict',
            options={'ordering': ('symbol',), 'verbose_name': 'Бинари', 'verbose_name_plural': 'Бинари'},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('is_current', models.BooleanField(default=False, verbose_name='Правильный ли ответ?')),
                ('type_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeanswer', verbose_name='Тип ответа')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
    ]
