# Generated by Django 4.0 on 2023-10-25 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='book_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verdict',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='verdict_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmember',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_book', to='api.book', verbose_name='Книга'),
        ),
    ]
