# Generated by Django 4.1.4 on 2023-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_typeanswer_alter_binarydict_options_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwriting',
            name='binary',
            field=models.TextField(verbose_name='Бинарное представление'),
        ),
        migrations.AlterField(
            model_name='handwriting',
            name='performance',
            field=models.TextField(verbose_name='16 представление'),
        ),
    ]
