# Generated by Django 4.0 on 2023-10-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_image_book_slug_verdict_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_verdict', to='api.verdict', verbose_name='Вердикт'),
        ),
    ]
