# Generated by Django 4.1.4 on 2023-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_handwriting_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='argument',
            field=models.TextField(blank=True, null=True, verbose_name='Аргумент'),
        ),
    ]
