# Generated by Django 4.1.4 on 2023-07-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'Типы вопроса',
                'db_table': 'type_questions',
            },
        ),
        migrations.AlterField(
            model_name='typeanswer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typequestion', verbose_name='Тип вопроса'),
        ),
    ]
