# Generated by Django 4.1.4 on 2023-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(default=1, max_length=255, verbose_name='Ip-адресс'),
            preserve_default=False,
        ),
    ]
