# Generated by Django 4.0 on 2023-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.AddField(
            model_name='code',
            name='email',
            field=models.CharField(default=1, max_length=255, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
