# Generated by Django 4.0 on 2023-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(choices=[('Key keeper', 'Ключник'), ('Centurion', 'Сотник'), ("Ten's manager", 'Десятник'), ('User', 'Пользователь')], max_length=150, verbose_name='пользователь'),
        ),
    ]
